export const inputs = {
    //Dados básicos
    charName: document.querySelector('input[name="charname"]'),
    classLevel: document.querySelector('input[name="classlevel"]'),
    background: document.querySelector('input[name="background"]'),
    playerName: document.querySelector('input[name="playername"]'),
    race: document.querySelector('input[name="race"]'),
    alignment: document.querySelector('input[name="alignment"]'),
    experiencePoints: document.querySelector('input[name="experiencepoints"]'),

    // Atributos
    strengthscore: document.querySelector('input[name="strengthscore"]'),
    strengthmod: document.querySelector('input[name="strengthmod"]'),
    dexterityscore: document.querySelector('input[name="dexterityscore"]'),
    dexteritymod: document.querySelector('input[name="dexteritymod"]'),
    constitutionscore: document.querySelector('input[name="constitutionscore"]'),
    constitutionmod: document.querySelector('input[name="constitutionmod"]'),
    wisdomscore: document.querySelector('input[name="wisdomscore"]'),
    wisdommod: document.querySelector('input[name="wisdommod"]'),
    intelligencescore: document.querySelector('input[name="intelligencescore"]'),
    intelligencemod: document.querySelector('input[name="intelligencemod"]'),
    charismascore: document.querySelector('input[name="charismascore"]'),
    charismamod: document.querySelector('input[name="charismamod"]'),


    inspiration: document.querySelector('input[name="inspiration"]'),
    proficiencyBonus: document.querySelector('input[name="proficiencybonus"]'),


    strengthsave: document.querySelector('input[name="Strength-save"]'),
    strengthsaveprof: document.querySelector('input[name="Strength-save-prof"]'),
    dexteritysave: document.querySelector('input[name="Dexterity-save"]'),
    dexteritysaveprof: document.querySelector('input[name="Dexterity-save-prof"]'),
    constitutionsave: document.querySelector('input[name="Constitution-save"]'),
    constitutionsaveprof: document.querySelector('input[name="Constitution-save-prof"]'),
    wisdomsave: document.querySelector('input[name="Wisdom-save"]'),
    wisdomsaveprof: document.querySelector('input[name="Wisdom-save-prof"]'),
    intelligencesave: document.querySelector('input[name="Intelligence-save"]'),
    intelligencesaveprof: document.querySelector('input[name="Intelligence-save-prof"]'),
    charismasave: document.querySelector('input[name="Charisma-save"]'),
    charismasaveprof: document.querySelector('input[name="Charisma-save-prof"]'),

    acrobatics: document.querySelector('input[name="Acrobatics"]'),
    acrobaticsprof: document.querySelector('input[name="Acrobatics-prof"]'),
    animalhandling: document.querySelector('input[name="Animal Handling"]'),
    animalhandlingprof: document.querySelector('input[name="Animal Handling-prof"]'),
    arcana: document.querySelector('input[name="Arcana"]'),
    arcanaprof: document.querySelector('input[name="Arcana-prof"]'),
    athletics: document.querySelector('input[name="Athletics"]'),
    athleticsprof: document.querySelector('input[name="Athletics-prof"]'),
    deception: document.querySelector('input[name="Deception"]'),
    deceptionprof: document.querySelector('input[name="Deception-prof"]'),
    history: document.querySelector('input[name="History"]'),
    historyprof: document.querySelector('input[name="History-prof"]'),
    insight: document.querySelector('input[name="Insight"]'),
    insightprof: document.querySelector('input[name="Insight-prof"]'),
    intimidation: document.querySelector('input[name="Intimidation"]'),
    intimidationprof: document.querySelector('input[name="Intimidation-prof"]'),
    investigation: document.querySelector('input[name="Investigation"]'),
    investigationprof: document.querySelector('input[name="Investigation-prof"]'),
    medicine: document.querySelector('input[name="Medicine"]'),
    medicineprof: document.querySelector('input[name="Medicine-prof"]'),
    nature: document.querySelector('input[name="Nature"]'),
    natureprof: document.querySelector('input[name="Nature-prof"]'),
    perception: document.querySelector('input[name="Perception"]'),
    perceptionprof: document.querySelector('input[name="Perception-prof"]'),
    performance: document.querySelector('input[name="Performance"]'),
    performanceprof: document.querySelector('input[name="Performance-prof"]'),
    persuasion: document.querySelector('input[name="Persuasion"]'),
    persuasionprof: document.querySelector('input[name="Persuasion-prof"]'),
    religion: document.querySelector('input[name="Religion"]'),
    religionprof: document.querySelector('input[name="Religion-prof"]'),
    sleightofhand: document.querySelector('input[name="Sleight of Hand"]'),
    sleightofhandprof: document.querySelector('input[name="Sleight of Hand-prof"]'),
    stealth: document.querySelector('input[name="Stealth"]'),
    stealthprof: document.querySelector('input[name="Stealth-prof"]'),
    survival: document.querySelector('input[name="Survival"]'),
    survivalprof: document.querySelector('input[name="Survival-prof"]'),
    passiveperception: document.querySelector('input[name="passiveperception"]'),
    otherprofs: document.querySelector('textarea[name="otherprofs"]'),
    ac: document.querySelector('input[name="ac"]'),
    initiative: document.querySelector('input[name="initiative"]'),
    speed: document.querySelector('input[name="speed"]'),
    maxHp: document.querySelector('input[name="maxhp"]'),

    // Armas
    weaponList: document.querySelector('#weaponsList tbody'),
    equipment: document.querySelector('textarea[placeholder="Equipment list here"]'),
    cp: document.querySelector('input[name="cp"]'),
    sp: document.querySelector('input[name="sp"]'),
    ep: document.querySelector('input[name="ep"]'),
    gp: document.querySelector('input[name="gp"]'),
    pp: document.querySelector('input[name="pp"]'),
    personality: document.querySelector('textarea[name="personality"]'),
    ideals: document.querySelector('textarea[name="ideals"]'),
    bonds: document.querySelector('textarea[name="bonds"]'),
    flaws: document.querySelector('textarea[name="flaws"]'),
    features: document.querySelector('textarea[name="features"]'),

    notes: document.querySelector('textarea[name="notes"]')
};